### ISSUE TITLE
how to check permissions on client side ?

### ISSUE THREAD

**Issue by dagatsoin** [miguelalarcos/roles-e#3]
Is there a way to check permissions on client side ? 
Per exemple on a angular 
<form ng-show="roleE.can(userId, 'insert', doc)" >

Since roleE is inaccessible on client side, I wonder if you have a workaround ?

**Comment by miguelalarcos** [comment]
I am very sorry for the late reply.

How would you think it should be the API client side? I don't have any workaround yet...

**Comment by miguelalarcos** [comment]
Hi, I'm trying to implement something like this in client side:

``` html
{{#if canInsert this 'posts'}}
      you can insert
{{/if}}
```

Is it something you were thinking in?

**Comment by miguelalarcos** [comment]
And also thinking in implement a `canSave` and `canRemove` methods in my package `simple-binding`.

You would use like this (`jade` code):

``` jade
span(sb sb-visible='canSave')
    input(type='text' sb sb-bind='surname')
    button(sb sb-click='save' sb-visible='isValid') save
```
